name: 🎨 Feature Request
description: Ask for something new
title: "[Feature]: "
labels: ["feature", "suggestion"]
assignees:
  - metzgr
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
 - type: textarea
  attributes:
    label: Request
    description: Tell us about your need or suggestion.
    placeholder: ex. I want to browse goals by administration
  validations:
    required: true
  - type: dropdown
    id: importance
    attributes:
      label: How important is this to you?
      multiple: false
      options:
        - Nice-to-have
        - Important
        - Critical
