name: 🎨 Request
description: Ask for something new
title: "[Request]: "
labels: ["new"]
assignees:
  - metzgr
body:
  - type: markdown
    attributes:
      value: |
        Communicate needs and suggestions. We'll consider your request alongside other priorities.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-request
    attributes:
      label: Request
      description: Describe your request.
      value: "What, where, and why?"
    validations:
      required: true
- type: textarea
    id: user-story
    attributes:
      label: Request
      description: Describe a user story and acceptance criteria.
      value: As a (type of user), I want to (something), so that I can (achieve goal]. Given I am on (webpage), When I (action), Then (result)
    validations:
      required: false
  - type: dropdown
    id: importance
    attributes:
      label: How important is this to you?
      description: Help us prioritize
      options:
        - Nice-to-have
        - Important
        - Critical
    validations:
      required: true
